//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mask
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://omniticket.network/ovw7", ConfigurationName="Mask.IWsAPIMask")]
    public interface IWsAPIMask
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#FindAllAccountCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.FindAllAccountCategoriesResponse FindAllAccountCategories(Mask.FindAllAccountCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#FindAllAccountCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.FindAllAccountCategoriesResponse> FindAllAccountCategoriesAsync(Mask.FindAllAccountCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadAccountCategoryByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.ReadAccountCategoryByCodeResponse ReadAccountCategoryByCode(Mask.ReadAccountCategoryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadAccountCategoryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.ReadAccountCategoryByCodeResponse> ReadAccountCategoryByCodeAsync(Mask.ReadAccountCategoryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadAccountCategoryByAK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.ReadAccountCategoryByAKResponse ReadAccountCategoryByAK(Mask.ReadAccountCategoryByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadAccountCategoryByAK", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.ReadAccountCategoryByAKResponse> ReadAccountCategoryByAKAsync(Mask.ReadAccountCategoryByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadExtendedInfoByAK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.ReadExtendedInfoByAKResponse ReadExtendedInfoByAK(Mask.ReadExtendedInfoByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadExtendedInfoByAK", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.ReadExtendedInfoByAKResponse> ReadExtendedInfoByAKAsync(Mask.ReadExtendedInfoByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadExtendedInfoByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.ReadExtendedInfoByCodeResponse ReadExtendedInfoByCode(Mask.ReadExtendedInfoByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadExtendedInfoByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.ReadExtendedInfoByCodeResponse> ReadExtendedInfoByCodeAsync(Mask.ReadExtendedInfoByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadDataProviderByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.ReadDataProviderByCodeResponse ReadDataProviderByCode(Mask.ReadDataProviderByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadDataProviderByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.ReadDataProviderByCodeResponse> ReadDataProviderByCodeAsync(Mask.ReadDataProviderByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadImageByAK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIELD[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MASK[]))]
        Mask.ReadImageByAKResponse ReadImageByAK(Mask.ReadImageByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIMaskIntf-IWsAPIMask#ReadImageByAK", ReplyAction="*")]
        System.Threading.Tasks.Task<Mask.ReadImageByAKResponse> ReadImageByAKAsync(Mask.ReadImageByAKRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class FINDALLACCOUNTCATEGORIESRESP
    {
        
        private ERROR eRRORField;
        
        private DMGCATEGORYINFO[] dMGCATEGORYLISTField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DMGCATEGORY", IsNullable=false)]
        public DMGCATEGORYINFO[] DMGCATEGORYLIST
        {
            get
            {
                return this.dMGCATEGORYLISTField;
            }
            set
            {
                this.dMGCATEGORYLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class ERROR
    {
        
        private string cODEField;
        
        private string tYPEField;
        
        private string tEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        public string TEXT
        {
            get
            {
                return this.tEXTField;
            }
            set
            {
                this.tEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READIMAGEBYAKRESP
    {
        
        private ERROR eRRORField;
        
        private READIMAGEBYAKRESPIMAGE iMAGEField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public READIMAGEBYAKRESPIMAGE IMAGE
        {
            get
            {
                return this.iMAGEField;
            }
            set
            {
                this.iMAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class READIMAGEBYAKRESPIMAGE
    {
        
        private string vALUEField;
        
        private string fILENAMEField;
        
        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        public string FILENAME
        {
            get
            {
                return this.fILENAMEField;
            }
            set
            {
                this.fILENAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class DIMENSION
    {
        
        private DIMENSIONCOMPONENT cOMPONENTField;
        
        private DIMENSIONATTRIBUTE aTTRIBUTEField;
        
        /// <remarks/>
        public DIMENSIONCOMPONENT COMPONENT
        {
            get
            {
                return this.cOMPONENTField;
            }
            set
            {
                this.cOMPONENTField = value;
            }
        }
        
        /// <remarks/>
        public DIMENSIONATTRIBUTE ATTRIBUTE
        {
            get
            {
                return this.aTTRIBUTEField;
            }
            set
            {
                this.aTTRIBUTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class DIMENSIONCOMPONENT
    {
        
        private string nAMEField;
        
        private string cODEField;
        
        /// <remarks/>
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class DIMENSIONATTRIBUTE
    {
        
        private string nAMEField;
        
        private string cODEField;
        
        /// <remarks/>
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READDATAPROVIDERBYCODERESP
    {
        
        private ERROR eRRORField;
        
        private READDATAPROVIDERBYCODERESPDATAPROVIDER dATAPROVIDERField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public READDATAPROVIDERBYCODERESPDATAPROVIDER DATAPROVIDER
        {
            get
            {
                return this.dATAPROVIDERField;
            }
            set
            {
                this.dATAPROVIDERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class READDATAPROVIDERBYCODERESPDATAPROVIDER
    {
        
        private string cODEField;
        
        private string nAMEField;
        
        private READDATAPROVIDERBYCODERESPDATAPROVIDERITEM[] iTEMLISTField;
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", IsNullable=false)]
        public READDATAPROVIDERBYCODERESPDATAPROVIDERITEM[] ITEMLIST
        {
            get
            {
                return this.iTEMLISTField;
            }
            set
            {
                this.iTEMLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class READDATAPROVIDERBYCODERESPDATAPROVIDERITEM
    {
        
        private string cODEField;
        
        private string dESCRIPTIONField;
        
        private int sORTORDERField;
        
        private string aDDITIONALCODEField;
        
        private DIMENSION dIMENSIONField;
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION
        {
            get
            {
                return this.dESCRIPTIONField;
            }
            set
            {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public int SORTORDER
        {
            get
            {
                return this.sORTORDERField;
            }
            set
            {
                this.sORTORDERField = value;
            }
        }
        
        /// <remarks/>
        public string ADDITIONALCODE
        {
            get
            {
                return this.aDDITIONALCODEField;
            }
            set
            {
                this.aDDITIONALCODEField = value;
            }
        }
        
        /// <remarks/>
        public DIMENSION DIMENSION
        {
            get
            {
                return this.dIMENSIONField;
            }
            set
            {
                this.dIMENSIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READEXTENEDINFOBYCODERESP
    {
        
        private ERROR eRRORField;
        
        private DMGCATEGORYINFO dMGCATEGORYField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public DMGCATEGORYINFO DMGCATEGORY
        {
            get
            {
                return this.dMGCATEGORYField;
            }
            set
            {
                this.dMGCATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class DMGCATEGORYINFO
    {
        
        private string cODEField;
        
        private string tYPEField;
        
        private string idField;
        
        private string nAMEField;
        
        private string dESCRIPTIONField;
        
        private MASK[] mASKLISTField;
        
        private string akField;
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION
        {
            get
            {
                return this.dESCRIPTIONField;
            }
            set
            {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MASK[] MASKLIST
        {
            get
            {
                return this.mASKLISTField;
            }
            set
            {
                this.mASKLISTField = value;
            }
        }
        
        /// <remarks/>
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class MASK
    {
        
        private string nAMEField;
        
        private string dESCRIPTIONField;
        
        private string idField;
        
        private FIELD[] fIELDLISTField;
        
        private string akField;
        
        /// <remarks/>
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION
        {
            get
            {
                return this.dESCRIPTIONField;
            }
            set
            {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FIELD[] FIELDLIST
        {
            get
            {
                return this.fIELDLISTField;
            }
            set
            {
                this.fIELDLISTField = value;
            }
        }
        
        /// <remarks/>
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class FIELD
    {
        
        private string sEARCHTYPEField;
        
        private string dEFAULTVALUEField;
        
        private string lABELField;
        
        private string oBJTYPEField;
        
        private string dATATYPEField;
        
        private string fIELDTYPEField;
        
        private I18N[] i18NLISTField;
        
        private string fILTERLISTField;
        
        private string dATAPROVIDERField;
        
        private string vISIBLELVField;
        
        private string eDITLVField;
        
        private VALIDATION vALIDATIONField;
        
        private DISPLAY dISPLAYField;
        
        /// <remarks/>
        public string SEARCHTYPE
        {
            get
            {
                return this.sEARCHTYPEField;
            }
            set
            {
                this.sEARCHTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string DEFAULTVALUE
        {
            get
            {
                return this.dEFAULTVALUEField;
            }
            set
            {
                this.dEFAULTVALUEField = value;
            }
        }
        
        /// <remarks/>
        public string LABEL
        {
            get
            {
                return this.lABELField;
            }
            set
            {
                this.lABELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OBJTYPE
        {
            get
            {
                return this.oBJTYPEField;
            }
            set
            {
                this.oBJTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string DATATYPE
        {
            get
            {
                return this.dATATYPEField;
            }
            set
            {
                this.dATATYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FIELDTYPE
        {
            get
            {
                return this.fIELDTYPEField;
            }
            set
            {
                this.fIELDTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public I18N[] I18NLIST
        {
            get
            {
                return this.i18NLISTField;
            }
            set
            {
                this.i18NLISTField = value;
            }
        }
        
        /// <remarks/>
        public string FILTERLIST
        {
            get
            {
                return this.fILTERLISTField;
            }
            set
            {
                this.fILTERLISTField = value;
            }
        }
        
        /// <remarks/>
        public string DATAPROVIDER
        {
            get
            {
                return this.dATAPROVIDERField;
            }
            set
            {
                this.dATAPROVIDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VISIBLELV
        {
            get
            {
                return this.vISIBLELVField;
            }
            set
            {
                this.vISIBLELVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EDITLV
        {
            get
            {
                return this.eDITLVField;
            }
            set
            {
                this.eDITLVField = value;
            }
        }
        
        /// <remarks/>
        public VALIDATION VALIDATION
        {
            get
            {
                return this.vALIDATIONField;
            }
            set
            {
                this.vALIDATIONField = value;
            }
        }
        
        /// <remarks/>
        public DISPLAY DISPLAY
        {
            get
            {
                return this.dISPLAYField;
            }
            set
            {
                this.dISPLAYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class I18N
    {
        
        private string akField;
        
        private string cODEField;
        
        private I18NFIELD[] fIELDLISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FIELD", IsNullable=false)]
        public I18NFIELD[] FIELDLIST
        {
            get
            {
                return this.fIELDLISTField;
            }
            set
            {
                this.fIELDLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class I18NFIELD
    {
        
        private int oBJTYPEField;
        
        private string vALUEField;
        
        private string lABELField;
        
        private string fILENAMEField;
        
        private string fIELDTYPEField;
        
        /// <remarks/>
        public int OBJTYPE
        {
            get
            {
                return this.oBJTYPEField;
            }
            set
            {
                this.oBJTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        public string LABEL
        {
            get
            {
                return this.lABELField;
            }
            set
            {
                this.lABELField = value;
            }
        }
        
        /// <remarks/>
        public string FILENAME
        {
            get
            {
                return this.fILENAMEField;
            }
            set
            {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FIELDTYPE
        {
            get
            {
                return this.fIELDTYPEField;
            }
            set
            {
                this.fIELDTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class VALIDATION
    {
        
        private int mINLENGTHField;
        
        private int mAXLENGTHField;
        
        private bool rEQUIREDField;
        
        private int eQUALTOField;
        
        private bool eQUALTOFieldSpecified;
        
        private string dISPLAYFORMATField;
        
        private bool dIGITSField;
        
        private bool eMAILField;
        
        private bool lETTERSONLYField;
        
        private bool dATEField;
        
        private string mINField;
        
        private string mAXField;
        
        private string rANGEField;
        
        private bool aLPHANUMERICField;
        
        private VALIDATIONCHOICES cHOICESField;
        
        private VALIDATIONDEPENDS dEPENDSField;
        
        /// <remarks/>
        public int MINLENGTH
        {
            get
            {
                return this.mINLENGTHField;
            }
            set
            {
                this.mINLENGTHField = value;
            }
        }
        
        /// <remarks/>
        public int MAXLENGTH
        {
            get
            {
                return this.mAXLENGTHField;
            }
            set
            {
                this.mAXLENGTHField = value;
            }
        }
        
        /// <remarks/>
        public bool REQUIRED
        {
            get
            {
                return this.rEQUIREDField;
            }
            set
            {
                this.rEQUIREDField = value;
            }
        }
        
        /// <remarks/>
        public int EQUALTO
        {
            get
            {
                return this.eQUALTOField;
            }
            set
            {
                this.eQUALTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EQUALTOSpecified
        {
            get
            {
                return this.eQUALTOFieldSpecified;
            }
            set
            {
                this.eQUALTOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DISPLAYFORMAT
        {
            get
            {
                return this.dISPLAYFORMATField;
            }
            set
            {
                this.dISPLAYFORMATField = value;
            }
        }
        
        /// <remarks/>
        public bool DIGITS
        {
            get
            {
                return this.dIGITSField;
            }
            set
            {
                this.dIGITSField = value;
            }
        }
        
        /// <remarks/>
        public bool EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public bool LETTERSONLY
        {
            get
            {
                return this.lETTERSONLYField;
            }
            set
            {
                this.lETTERSONLYField = value;
            }
        }
        
        /// <remarks/>
        public bool DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MIN
        {
            get
            {
                return this.mINField;
            }
            set
            {
                this.mINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MAX
        {
            get
            {
                return this.mAXField;
            }
            set
            {
                this.mAXField = value;
            }
        }
        
        /// <remarks/>
        public string RANGE
        {
            get
            {
                return this.rANGEField;
            }
            set
            {
                this.rANGEField = value;
            }
        }
        
        /// <remarks/>
        public bool ALPHANUMERIC
        {
            get
            {
                return this.aLPHANUMERICField;
            }
            set
            {
                this.aLPHANUMERICField = value;
            }
        }
        
        /// <remarks/>
        public VALIDATIONCHOICES CHOICES
        {
            get
            {
                return this.cHOICESField;
            }
            set
            {
                this.cHOICESField = value;
            }
        }
        
        /// <remarks/>
        public VALIDATIONDEPENDS DEPENDS
        {
            get
            {
                return this.dEPENDSField;
            }
            set
            {
                this.dEPENDSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class VALIDATIONCHOICES
    {
        
        private string mINField;
        
        private string mAXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MIN
        {
            get
            {
                return this.mINField;
            }
            set
            {
                this.mINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MAX
        {
            get
            {
                return this.mAXField;
            }
            set
            {
                this.mAXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class VALIDATIONDEPENDS
    {
        
        private string vALUEField;
        
        private int cHECKTYPEField;
        
        private int oBJTYPEField;
        
        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        public int CHECKTYPE
        {
            get
            {
                return this.cHECKTYPEField;
            }
            set
            {
                this.cHECKTYPEField = value;
            }
        }
        
        /// <remarks/>
        public int OBJTYPE
        {
            get
            {
                return this.oBJTYPEField;
            }
            set
            {
                this.oBJTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class DISPLAY
    {
        
        private string cOLUMNField;
        
        private string rOWField;
        
        private string cOLSPANField;
        
        private string wIDTHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string COLUMN
        {
            get
            {
                return this.cOLUMNField;
            }
            set
            {
                this.cOLUMNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ROW
        {
            get
            {
                return this.rOWField;
            }
            set
            {
                this.rOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string COLSPAN
        {
            get
            {
                return this.cOLSPANField;
            }
            set
            {
                this.cOLSPANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string WIDTH
        {
            get
            {
                return this.wIDTHField;
            }
            set
            {
                this.wIDTHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READEXTENEDINFOBYAKRESP
    {
        
        private ERROR eRRORField;
        
        private DMGCATEGORYINFO dMGCATEGORYField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public DMGCATEGORYINFO DMGCATEGORY
        {
            get
            {
                return this.dMGCATEGORYField;
            }
            set
            {
                this.dMGCATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READACCOUNTCATEGORYBYAKRESP
    {
        
        private ERROR eRRORField;
        
        private DMGCATEGORYINFO dMGCATEGORYField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public DMGCATEGORYINFO DMGCATEGORY
        {
            get
            {
                return this.dMGCATEGORYField;
            }
            set
            {
                this.dMGCATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READACCOUNTCATEGORYBYCODERESP
    {
        
        private ERROR eRRORField;
        
        private DMGCATEGORYINFO dMGCATEGORYField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public DMGCATEGORYINFO DMGCATEGORY
        {
            get
            {
                return this.dMGCATEGORYField;
            }
            set
            {
                this.dMGCATEGORYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllAccountCategories", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class FindAllAccountCategoriesRequest
    {
        
        public FindAllAccountCategoriesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllAccountCategoriesResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class FindAllAccountCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.FINDALLACCOUNTCATEGORIESRESP @return;
        
        public FindAllAccountCategoriesResponse()
        {
        }
        
        public FindAllAccountCategoriesResponse(Mask.FINDALLACCOUNTCATEGORIESRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAccountCategoryByCode", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadAccountCategoryByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ADmgCategoryCode;
        
        public ReadAccountCategoryByCodeRequest()
        {
        }
        
        public ReadAccountCategoryByCodeRequest(string ADmgCategoryCode)
        {
            this.ADmgCategoryCode = ADmgCategoryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAccountCategoryByCodeResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadAccountCategoryByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.READACCOUNTCATEGORYBYCODERESP @return;
        
        public ReadAccountCategoryByCodeResponse()
        {
        }
        
        public ReadAccountCategoryByCodeResponse(Mask.READACCOUNTCATEGORYBYCODERESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAccountCategoryByAK", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadAccountCategoryByAKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ADmgCategoryAK;
        
        public ReadAccountCategoryByAKRequest()
        {
        }
        
        public ReadAccountCategoryByAKRequest(string ADmgCategoryAK)
        {
            this.ADmgCategoryAK = ADmgCategoryAK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAccountCategoryByAKResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadAccountCategoryByAKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.READACCOUNTCATEGORYBYAKRESP @return;
        
        public ReadAccountCategoryByAKResponse()
        {
        }
        
        public ReadAccountCategoryByAKResponse(Mask.READACCOUNTCATEGORYBYAKRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadExtendedInfoByAK", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadExtendedInfoByAKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ADmgCategoryAK;
        
        public ReadExtendedInfoByAKRequest()
        {
        }
        
        public ReadExtendedInfoByAKRequest(string ADmgCategoryAK)
        {
            this.ADmgCategoryAK = ADmgCategoryAK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadExtendedInfoByAKResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadExtendedInfoByAKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.READEXTENEDINFOBYAKRESP @return;
        
        public ReadExtendedInfoByAKResponse()
        {
        }
        
        public ReadExtendedInfoByAKResponse(Mask.READEXTENEDINFOBYAKRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadExtendedInfoByCode", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadExtendedInfoByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ADmgCategoryCode;
        
        public ReadExtendedInfoByCodeRequest()
        {
        }
        
        public ReadExtendedInfoByCodeRequest(string ADmgCategoryCode)
        {
            this.ADmgCategoryCode = ADmgCategoryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadExtendedInfoByCodeResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadExtendedInfoByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.READEXTENEDINFOBYCODERESP @return;
        
        public ReadExtendedInfoByCodeResponse()
        {
        }
        
        public ReadExtendedInfoByCodeResponse(Mask.READEXTENEDINFOBYCODERESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataProviderByCode", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadDataProviderByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ADataProviderCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ALangCode;
        
        public ReadDataProviderByCodeRequest()
        {
        }
        
        public ReadDataProviderByCodeRequest(string ADataProviderCode, string ALangCode)
        {
            this.ADataProviderCode = ADataProviderCode;
            this.ALangCode = ALangCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataProviderByCodeResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadDataProviderByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.READDATAPROVIDERBYCODERESP @return;
        
        public ReadDataProviderByCodeResponse()
        {
        }
        
        public ReadDataProviderByCodeResponse(Mask.READDATAPROVIDERBYCODERESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadImageByAK", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadImageByAKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AImageAK;
        
        public ReadImageByAKRequest()
        {
        }
        
        public ReadImageByAKRequest(string AImageAK)
        {
            this.AImageAK = AImageAK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadImageByAKResponse", WrapperNamespace="urn:WsAPIMaskIntf-IWsAPIMask", IsWrapped=true)]
    public partial class ReadImageByAKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Mask.READIMAGEBYAKRESP @return;
        
        public ReadImageByAKResponse()
        {
        }
        
        public ReadImageByAKResponse(Mask.READIMAGEBYAKRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWsAPIMaskChannel : Mask.IWsAPIMask, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WsAPIMaskClient : System.ServiceModel.ClientBase<Mask.IWsAPIMask>, Mask.IWsAPIMask
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsAPIMaskClient() : 
                base(WsAPIMaskClient.GetDefaultBinding(), WsAPIMaskClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IWsAPIMaskPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIMaskClient(EndpointConfiguration endpointConfiguration) : 
                base(WsAPIMaskClient.GetBindingForEndpoint(endpointConfiguration), WsAPIMaskClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIMaskClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsAPIMaskClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIMaskClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsAPIMaskClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIMaskClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Mask.FindAllAccountCategoriesResponse FindAllAccountCategories(Mask.FindAllAccountCategoriesRequest request)
        {
            return base.Channel.FindAllAccountCategories(request);
        }
        
        public System.Threading.Tasks.Task<Mask.FindAllAccountCategoriesResponse> FindAllAccountCategoriesAsync(Mask.FindAllAccountCategoriesRequest request)
        {
            return base.Channel.FindAllAccountCategoriesAsync(request);
        }
        
        public Mask.ReadAccountCategoryByCodeResponse ReadAccountCategoryByCode(Mask.ReadAccountCategoryByCodeRequest request)
        {
            return base.Channel.ReadAccountCategoryByCode(request);
        }
        
        public System.Threading.Tasks.Task<Mask.ReadAccountCategoryByCodeResponse> ReadAccountCategoryByCodeAsync(Mask.ReadAccountCategoryByCodeRequest request)
        {
            return base.Channel.ReadAccountCategoryByCodeAsync(request);
        }
        
        public Mask.ReadAccountCategoryByAKResponse ReadAccountCategoryByAK(Mask.ReadAccountCategoryByAKRequest request)
        {
            return base.Channel.ReadAccountCategoryByAK(request);
        }
        
        public System.Threading.Tasks.Task<Mask.ReadAccountCategoryByAKResponse> ReadAccountCategoryByAKAsync(Mask.ReadAccountCategoryByAKRequest request)
        {
            return base.Channel.ReadAccountCategoryByAKAsync(request);
        }
        
        public Mask.ReadExtendedInfoByAKResponse ReadExtendedInfoByAK(Mask.ReadExtendedInfoByAKRequest request)
        {
            return base.Channel.ReadExtendedInfoByAK(request);
        }
        
        public System.Threading.Tasks.Task<Mask.ReadExtendedInfoByAKResponse> ReadExtendedInfoByAKAsync(Mask.ReadExtendedInfoByAKRequest request)
        {
            return base.Channel.ReadExtendedInfoByAKAsync(request);
        }
        
        public Mask.ReadExtendedInfoByCodeResponse ReadExtendedInfoByCode(Mask.ReadExtendedInfoByCodeRequest request)
        {
            return base.Channel.ReadExtendedInfoByCode(request);
        }
        
        public System.Threading.Tasks.Task<Mask.ReadExtendedInfoByCodeResponse> ReadExtendedInfoByCodeAsync(Mask.ReadExtendedInfoByCodeRequest request)
        {
            return base.Channel.ReadExtendedInfoByCodeAsync(request);
        }
        
        public Mask.ReadDataProviderByCodeResponse ReadDataProviderByCode(Mask.ReadDataProviderByCodeRequest request)
        {
            return base.Channel.ReadDataProviderByCode(request);
        }
        
        public System.Threading.Tasks.Task<Mask.ReadDataProviderByCodeResponse> ReadDataProviderByCodeAsync(Mask.ReadDataProviderByCodeRequest request)
        {
            return base.Channel.ReadDataProviderByCodeAsync(request);
        }
        
        public Mask.ReadImageByAKResponse ReadImageByAK(Mask.ReadImageByAKRequest request)
        {
            return base.Channel.ReadImageByAK(request);
        }
        
        public System.Threading.Tasks.Task<Mask.ReadImageByAKResponse> ReadImageByAKAsync(Mask.ReadImageByAKRequest request)
        {
            return base.Channel.ReadImageByAKAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWsAPIMaskPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWsAPIMaskPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:23479/soap/IWsAPIMask?OvwSessionId=81938FE69B2F4189BF1D1F4570B94" +
                        "66A");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsAPIMaskClient.GetBindingForEndpoint(EndpointConfiguration.IWsAPIMaskPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsAPIMaskClient.GetEndpointAddress(EndpointConfiguration.IWsAPIMaskPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IWsAPIMaskPort,
        }
    }
}
