//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://omniticket.network/ovw7", ConfigurationName="Events.IWsAPIEvent")]
    public interface IWsAPIEvent
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#FindAllEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PAGEREQ))]
        Events.FindAllEventsResponse FindAllEvents(Events.FindAllEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#FindAllEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Events.FindAllEventsResponse> FindAllEventsAsync(Events.FindAllEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#ReadEventByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PAGEREQ))]
        Events.ReadEventByCodeResponse ReadEventByCode(Events.ReadEventByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#ReadEventByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Events.ReadEventByCodeResponse> ReadEventByCodeAsync(Events.ReadEventByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#ReadEventByAK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PAGEREQ))]
        Events.ReadEventByAKResponse ReadEventByAK(Events.ReadEventByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#ReadEventByAK", ReplyAction="*")]
        System.Threading.Tasks.Task<Events.ReadEventByAKResponse> ReadEventByAKAsync(Events.ReadEventByAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#FindAllEventCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PAGEREQ))]
        Events.FindAllEventCategoryResponse FindAllEventCategory(Events.FindAllEventCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#FindAllEventCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<Events.FindAllEventCategoryResponse> FindAllEventCategoryAsync(Events.FindAllEventCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#FindEventsByAccountAK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PAGEREQ))]
        Events.FindEventsByAccountAKResponse FindEventsByAccountAK(Events.FindEventsByAccountAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#FindEventsByAccountAK", ReplyAction="*")]
        System.Threading.Tasks.Task<Events.FindEventsByAccountAKResponse> FindEventsByAccountAKAsync(Events.FindEventsByAccountAKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#SearchEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PAGEREQ))]
        Events.SearchEventResponse SearchEvent(Events.SearchEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsAPIEventIntf-IWsAPIEvent#SearchEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Events.SearchEventResponse> SearchEventAsync(Events.SearchEventRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class FINDALLEVENTSRESP
    {
        
        private ERROR eRRORField;
        
        private FINDALLEVENTSRESPEVENTLIST eVENTLISTField;

        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public FINDALLEVENTSRESPEVENTLIST EVENTLIST
        {
            get
            {
                return this.eVENTLISTField;
            }
            set
            {
                this.eVENTLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class ERROR
    {
        
        private string cODEField;
        
        private string tYPEField;
        
        private string tEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        public string TEXT
        {
            get
            {
                return this.tEXTField;
            }
            set
            {
                this.tEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class PAGERESP
    {
        
        private string pAGEINDEXField;
        
        private string pAGECOUNTField;
        
        private string pAGESIZEField;
        
        private string rECORDCOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PAGEINDEX
        {
            get
            {
                return this.pAGEINDEXField;
            }
            set
            {
                this.pAGEINDEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PAGECOUNT
        {
            get
            {
                return this.pAGECOUNTField;
            }
            set
            {
                this.pAGECOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PAGESIZE
        {
            get
            {
                return this.pAGESIZEField;
            }
            set
            {
                this.pAGESIZEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RECORDCOUNT
        {
            get
            {
                return this.rECORDCOUNTField;
            }
            set
            {
                this.rECORDCOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class AVAILABILITY
    {
        
        private string tOTALField;
        
        private string aVAILABLEField;
        
        private bool gENERALADMISSIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TOTAL
        {
            get
            {
                return this.tOTALField;
            }
            set
            {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string AVAILABLE
        {
            get
            {
                return this.aVAILABLEField;
            }
            set
            {
                this.aVAILABLEField = value;
            }
        }
        
        /// <remarks/>
        public bool GENERALADMISSION
        {
            get
            {
                return this.gENERALADMISSIONField;
            }
            set
            {
                this.gENERALADMISSIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class SEARCHEVENTRESP
    {
        
        private ERROR eRRORField;
        
        private SEARCHEVENTRESPEVENTLIST eVENTLISTField;
        
        private PAGERESP pAGERESPField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public SEARCHEVENTRESPEVENTLIST EVENTLIST
        {
            get
            {
                return this.eVENTLISTField;
            }
            set
            {
                this.eVENTLISTField = value;
            }
        }
        
        /// <remarks/>
        public PAGERESP PAGERESP
        {
            get
            {
                return this.pAGERESPField;
            }
            set
            {
                this.pAGERESPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class SEARCHEVENTRESPEVENTLIST
    {
        
        private SEARCHEVENTRESPEVENTLISTEVENT eVENTField;
        
        /// <remarks/>
        public SEARCHEVENTRESPEVENTLISTEVENT EVENT
        {
            get
            {
                return this.eVENTField;
            }
            set
            {
                this.eVENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class SEARCHEVENTRESPEVENTLISTEVENT : EVENT
    {
        
        private bool sELLABLEField;
        
        private AVAILABILITY aVAILABILITYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool SELLABLE
        {
            get
            {
                return this.sELLABLEField;
            }
            set
            {
                this.sELLABLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AVAILABILITY AVAILABILITY
        {
            get
            {
                return this.aVAILABILITYField;
            }
            set
            {
                this.aVAILABILITYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class EVENT
    {
        
        private string akField;
        
        private string cODEField;
        
        private System.DateTime sTARTDATEField;
        
        private System.DateTime eNDDATEField;
        
        private LOCATIONBASE lOCATIONField;
        
        private I18N[] i18NLISTField;
        
        private int sTATUSField;
        
        private string mAXPERTRANSACTIONField;
        
        private EVENTEVENTCATEGORYLIST eVENTCATEGORYLISTField;
        
        private int sORTORDERField;
        
        private bool sORTORDERFieldSpecified;
        
        private System.DateTime fIRSTSELLABLEPERFORMANCEDATEField;
        
        private bool fIRSTSELLABLEPERFORMANCEDATEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime STARTDATE
        {
            get
            {
                return this.sTARTDATEField;
            }
            set
            {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ENDDATE
        {
            get
            {
                return this.eNDDATEField;
            }
            set
            {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LOCATIONBASE LOCATION
        {
            get
            {
                return this.lOCATIONField;
            }
            set
            {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public I18N[] I18NLIST
        {
            get
            {
                return this.i18NLISTField;
            }
            set
            {
                this.i18NLISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string MAXPERTRANSACTION
        {
            get
            {
                return this.mAXPERTRANSACTIONField;
            }
            set
            {
                this.mAXPERTRANSACTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public EVENTEVENTCATEGORYLIST EVENTCATEGORYLIST
        {
            get
            {
                return this.eVENTCATEGORYLISTField;
            }
            set
            {
                this.eVENTCATEGORYLISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int SORTORDER
        {
            get
            {
                return this.sORTORDERField;
            }
            set
            {
                this.sORTORDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORTORDERSpecified
        {
            get
            {
                return this.sORTORDERFieldSpecified;
            }
            set
            {
                this.sORTORDERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime FIRSTSELLABLEPERFORMANCEDATE
        {
            get
            {
                return this.fIRSTSELLABLEPERFORMANCEDATEField;
            }
            set
            {
                this.fIRSTSELLABLEPERFORMANCEDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FIRSTSELLABLEPERFORMANCEDATESpecified
        {
            get
            {
                return this.fIRSTSELLABLEPERFORMANCEDATEFieldSpecified;
            }
            set
            {
                this.fIRSTSELLABLEPERFORMANCEDATEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class LOCATIONBASE
    {
        
        private string akField;
        
        private string cODEField;
        
        /// <remarks/>
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class I18N
    {
        
        private string akField;
        
        private string cODEField;
        
        private I18NFIELD[] fIELDLISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FIELD", IsNullable=false)]
        public I18NFIELD[] FIELDLIST
        {
            get
            {
                return this.fIELDLISTField;
            }
            set
            {
                this.fIELDLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class I18NFIELD
    {
        
        private int oBJTYPEField;
        
        private string vALUEField;
        
        private string lABELField;
        
        private string fILENAMEField;
        
        private string fIELDTYPEField;
        
        /// <remarks/>
        public int OBJTYPE
        {
            get
            {
                return this.oBJTYPEField;
            }
            set
            {
                this.oBJTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        public string LABEL
        {
            get
            {
                return this.lABELField;
            }
            set
            {
                this.lABELField = value;
            }
        }
        
        /// <remarks/>
        public string FILENAME
        {
            get
            {
                return this.fILENAMEField;
            }
            set
            {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FIELDTYPE
        {
            get
            {
                return this.fIELDTYPEField;
            }
            set
            {
                this.fIELDTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class EVENTEVENTCATEGORYLIST
    {
        
        private TAGBASE eVENTCATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TAGBASE EVENTCATEGORY
        {
            get
            {
                return this.eVENTCATEGORYField;
            }
            set
            {
                this.eVENTCATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TAG))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class TAGBASE
    {
        
        private string dESCRIPTIONField;
        
        private string cODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DESCRIPTION
        {
            get
            {
                return this.dESCRIPTIONField;
            }
            set
            {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class TAG : TAGBASE
    {
        
        private int pOSITIONField;
        
        private int lEVELField;
        
        private string pARENTCODEField;
        
        private bool aCTIVEField;
        
        private I18N[] i18NLISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int POSITION
        {
            get
            {
                return this.pOSITIONField;
            }
            set
            {
                this.pOSITIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LEVEL
        {
            get
            {
                return this.lEVELField;
            }
            set
            {
                this.lEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PARENTCODE
        {
            get
            {
                return this.pARENTCODEField;
            }
            set
            {
                this.pARENTCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ACTIVE
        {
            get
            {
                return this.aCTIVEField;
            }
            set
            {
                this.aCTIVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public I18N[] I18NLIST
        {
            get
            {
                return this.i18NLISTField;
            }
            set
            {
                this.i18NLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class PAGEREQ
    {
        
        private string pAGEINDEXField;
        
        private int pAGESIZEField;
        
        private PAGEREQSORTDIRECTION sORTDIRECTIONField;
        
        private bool sORTDIRECTIONFieldSpecified;
        
        public PAGEREQ()
        {
            this.pAGEINDEXField = "1";
            this.pAGESIZEField = 10;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string PAGEINDEX
        {
            get
            {
                return this.pAGEINDEXField;
            }
            set
            {
                this.pAGEINDEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int PAGESIZE
        {
            get
            {
                return this.pAGESIZEField;
            }
            set
            {
                this.pAGESIZEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PAGEREQSORTDIRECTION SORTDIRECTION
        {
            get
            {
                return this.sORTDIRECTIONField;
            }
            set
            {
                this.sORTDIRECTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORTDIRECTIONSpecified
        {
            get
            {
                return this.sORTDIRECTIONFieldSpecified;
            }
            set
            {
                this.sORTDIRECTIONFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public enum PAGEREQSORTDIRECTION
    {
        
        /// <remarks/>
        ASC,
        
        /// <remarks/>
        DESC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class CATEGORY
    {
        
        private string cODEField;
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class EVENTCATEGORYLIST
    {
        
        private CATEGORY eVENTCATEGORYField;
        
        /// <remarks/>
        public CATEGORY EVENTCATEGORY
        {
            get
            {
                return this.eVENTCATEGORYField;
            }
            set
            {
                this.eVENTCATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class EVENTBASE
    {
        
        private string cODEField;
        
        private string akField;
        
        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public string AK
        {
            get
            {
                return this.akField;
            }
            set
            {
                this.akField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]

    public partial class BASETIMEFILTER
    {
        
        private System.DateTime fROMField;
        
        private System.DateTime toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime FROM
        {
            get
            {
                return this.fROMField;
            }
            set
            {
                this.fROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime TO
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class BASEDATEFILTER
    {
        
        private System.DateTime fROMField;
        
        private System.DateTime toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FROM
        {
            get
            {
                return this.fROMField;
            }
            set
            {
                this.fROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime TO
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class SEARCHEVENTREQ
    {
        
        private BASEDATEFILTER dATEField;
        
        private BASETIMEFILTER tIMEField;
        
        private EVENTBASE[] eVENTLISTField;
        
        private EVENTCATEGORYLIST eVENTCATEGORYLISTField;
        
        private string lOCATIONAKField;
        
        private string aCCOUNTAKField;
        
        private SEARCHEVENTREQPAGEREQ pAGEREQField;
        
        private int eVENTSTATUSField;
        
        private bool eVENTSTATUSFieldSpecified;
        
        private string nUMBEROFPERSONField;
        
        /// <remarks/>
        public BASEDATEFILTER DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }
        
        /// <remarks/>
        public BASETIMEFILTER TIME
        {
            get
            {
                return this.tIMEField;
            }
            set
            {
                this.tIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public EVENTBASE[] EVENTLIST
        {
            get
            {
                return this.eVENTLISTField;
            }
            set
            {
                this.eVENTLISTField = value;
            }
        }
        
        /// <remarks/>
        public EVENTCATEGORYLIST EVENTCATEGORYLIST
        {
            get
            {
                return this.eVENTCATEGORYLISTField;
            }
            set
            {
                this.eVENTCATEGORYLISTField = value;
            }
        }
        
        /// <remarks/>
        public string LOCATIONAK
        {
            get
            {
                return this.lOCATIONAKField;
            }
            set
            {
                this.lOCATIONAKField = value;
            }
        }
        
        /// <remarks/>
        public string ACCOUNTAK
        {
            get
            {
                return this.aCCOUNTAKField;
            }
            set
            {
                this.aCCOUNTAKField = value;
            }
        }
        
        /// <remarks/>
        public SEARCHEVENTREQPAGEREQ PAGEREQ
        {
            get
            {
                return this.pAGEREQField;
            }
            set
            {
                this.pAGEREQField = value;
            }
        }
        
        /// <remarks/>
        public int EVENTSTATUS
        {
            get
            {
                return this.eVENTSTATUSField;
            }
            set
            {
                this.eVENTSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EVENTSTATUSSpecified
        {
            get
            {
                return this.eVENTSTATUSFieldSpecified;
            }
            set
            {
                this.eVENTSTATUSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NUMBEROFPERSON
        {
            get
            {
                return this.nUMBEROFPERSONField;
            }
            set
            {
                this.nUMBEROFPERSONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class SEARCHEVENTREQPAGEREQ : PAGEREQ
    {
        
        private SEARCHEVENTREQPAGEREQSORTFIELD sORTFIELDField;
        
        private bool sORTFIELDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SEARCHEVENTREQPAGEREQSORTFIELD SORTFIELD
        {
            get
            {
                return this.sORTFIELDField;
            }
            set
            {
                this.sORTFIELDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORTFIELDSpecified
        {
            get
            {
                return this.sORTFIELDFieldSpecified;
            }
            set
            {
                this.sORTFIELDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public enum SEARCHEVENTREQPAGEREQSORTFIELD
    {
        
        /// <remarks/>
        AK,
        
        /// <remarks/>
        DATETIME,
        
        /// <remarks/>
        NAME,
        
        /// <remarks/>
        STATUS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PRICETABLE.AK")]
        PRICETABLEAK,
        
        /// <remarks/>
        OPENINGTIME,
        
        /// <remarks/>
        CLOSINGTIME,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("EVENT.AK")]
        EVENTAK,
        
        /// <remarks/>
        OPENINGSALE,
        
        /// <remarks/>
        CLOSINGSALE,
        
        /// <remarks/>
        SELLABLE,
        
        /// <remarks/>
        BLOCKED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class FINDEVENTSBYACCOUNTAKRESP
    {
        
        private ERROR eRRORField;
        
        private FINDEVENTSBYACCOUNTAKRESPEVENTLIST eVENTLISTField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public FINDEVENTSBYACCOUNTAKRESPEVENTLIST EVENTLIST
        {
            get
            {
                return this.eVENTLISTField;
            }
            set
            {
                this.eVENTLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class FINDEVENTSBYACCOUNTAKRESPEVENTLIST
    {
        
        private EVENT eVENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EVENT EVENT
        {
            get
            {
                return this.eVENTField;
            }
            set
            {
                this.eVENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class FINDALLEVENTCATEGORYRESP
    {
        
        private ERROR eRRORField;
        
        private FINDALLEVENTCATEGORYRESPCATEGORYLIST cATEGORYLISTField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public FINDALLEVENTCATEGORYRESPCATEGORYLIST CATEGORYLIST
        {
            get
            {
                return this.cATEGORYLISTField;
            }
            set
            {
                this.cATEGORYLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class FINDALLEVENTCATEGORYRESPCATEGORYLIST
    {
        
        private TAG cATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TAG CATEGORY
        {
            get
            {
                return this.cATEGORYField;
            }
            set
            {
                this.cATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw7")]
    public partial class READEVENTBYAKRESP
    {
        
        private ERROR eRRORField;
        
        private EVENT eVENTField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public EVENT EVENT
        {
            get
            {
                return this.eVENTField;
            }
            set
            {
                this.eVENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniticket.network/ovw8")]
    public partial class READEVENTBYCODERESP
    {
        
        private ERROR eRRORField;
        
        private EVENT eVENTField;
        
        /// <remarks/>
        public ERROR ERROR
        {
            get
            {
                return this.eRRORField;
            }
            set
            {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public EVENT EVENT
        {
            get
            {
                return this.eVENTField;
            }
            set
            {
                this.eVENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://omniticket.network/ovw7")]
    public partial class FINDALLEVENTSRESPEVENTLIST
    {
        
        private EVENT eVENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EVENT EVENT
        {
            get
            {
                return this.eVENTField;
            }
            set
            {
                this.eVENTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllEvents", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class FindAllEventsRequest
    {
        
        public FindAllEventsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllEventsResponse", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    

    public partial class FindAllEventsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]

        public Events.FINDALLEVENTSRESP @return;
        
        public FindAllEventsResponse()
        {
        }
        
        public FindAllEventsResponse(Events.FINDALLEVENTSRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEventByCode", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class ReadEventByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public string AEventCode;
        
        public ReadEventByCodeRequest()
        {
        }
        
        public ReadEventByCodeRequest(string AEventCode)
        {
            this.AEventCode = AEventCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEventByCodeResponse", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class ReadEventByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public Events.READEVENTBYCODERESP @return;
        
        public ReadEventByCodeResponse()
        {
        }
        
        public ReadEventByCodeResponse(Events.READEVENTBYCODERESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEventByAK", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class ReadEventByAKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public string AEventAK;
        
        public ReadEventByAKRequest()
        {
        }
        
        public ReadEventByAKRequest(string AEventAK)
        {
            this.AEventAK = AEventAK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEventByAKResponse", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class ReadEventByAKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public Events.READEVENTBYAKRESP @return;
        
        public ReadEventByAKResponse()
        {
        }
        
        public ReadEventByAKResponse(Events.READEVENTBYAKRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllEventCategory", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class FindAllEventCategoryRequest
    {
        
        public FindAllEventCategoryRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllEventCategoryResponse", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class FindAllEventCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public Events.FINDALLEVENTCATEGORYRESP @return;
        
        public FindAllEventCategoryResponse()
        {
        }
        
        public FindAllEventCategoryResponse(Events.FINDALLEVENTCATEGORYRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEventsByAccountAK", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class FindEventsByAccountAKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public string AAccountAK;
        
        public FindEventsByAccountAKRequest()
        {
        }
        
        public FindEventsByAccountAKRequest(string AAccountAK)
        {
            this.AAccountAK = AAccountAK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEventsByAccountAKResponse", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class FindEventsByAccountAKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public Events.FINDEVENTSBYACCOUNTAKRESP @return;
        
        public FindEventsByAccountAKResponse()
        {
        }
        
        public FindEventsByAccountAKResponse(Events.FINDEVENTSBYACCOUNTAKRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchEvent", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class SearchEventRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public Events.SEARCHEVENTREQ SEARCHEVENTREQ;
        
        public SearchEventRequest()
        {
        }
        
        public SearchEventRequest(Events.SEARCHEVENTREQ SEARCHEVENTREQ)
        {
            this.SEARCHEVENTREQ = SEARCHEVENTREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchEventResponse", WrapperNamespace="urn:WsAPIEventIntf-IWsAPIEvent", IsWrapped=true)]
    public partial class SearchEventResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://omniticket.network/ovw7", Order=0)]
        public Events.SEARCHEVENTRESP @return;
        
        public SearchEventResponse()
        {
        }
        
        public SearchEventResponse(Events.SEARCHEVENTRESP @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWsAPIEventChannel : Events.IWsAPIEvent, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WsAPIEventClient : System.ServiceModel.ClientBase<Events.IWsAPIEvent>, Events.IWsAPIEvent
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsAPIEventClient() : 
                base(WsAPIEventClient.GetDefaultBinding(), WsAPIEventClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IWsAPIEventPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIEventClient(EndpointConfiguration endpointConfiguration) : 
                base(WsAPIEventClient.GetBindingForEndpoint(endpointConfiguration), WsAPIEventClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIEventClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsAPIEventClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIEventClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsAPIEventClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsAPIEventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Events.FindAllEventsResponse FindAllEvents(Events.FindAllEventsRequest request)
        {
            return base.Channel.FindAllEvents(request);
        }
        
        public System.Threading.Tasks.Task<Events.FindAllEventsResponse> FindAllEventsAsync(Events.FindAllEventsRequest request)
        {
            return base.Channel.FindAllEventsAsync(request);
        }
        
        public Events.ReadEventByCodeResponse ReadEventByCode(Events.ReadEventByCodeRequest request)
        {
            return base.Channel.ReadEventByCode(request);
        }
        
        public System.Threading.Tasks.Task<Events.ReadEventByCodeResponse> ReadEventByCodeAsync(Events.ReadEventByCodeRequest request)
        {
            return base.Channel.ReadEventByCodeAsync(request);
        }
        
        public Events.ReadEventByAKResponse ReadEventByAK(Events.ReadEventByAKRequest request)
        {
            return base.Channel.ReadEventByAK(request);
        }
        
        public System.Threading.Tasks.Task<Events.ReadEventByAKResponse> ReadEventByAKAsync(Events.ReadEventByAKRequest request)
        {
            return base.Channel.ReadEventByAKAsync(request);
        }
        
        public Events.FindAllEventCategoryResponse FindAllEventCategory(Events.FindAllEventCategoryRequest request)
        {
            return base.Channel.FindAllEventCategory(request);
        }
        
        public System.Threading.Tasks.Task<Events.FindAllEventCategoryResponse> FindAllEventCategoryAsync(Events.FindAllEventCategoryRequest request)
        {
            return base.Channel.FindAllEventCategoryAsync(request);
        }
        
        public Events.FindEventsByAccountAKResponse FindEventsByAccountAK(Events.FindEventsByAccountAKRequest request)
        {
            return base.Channel.FindEventsByAccountAK(request);
        }
        
        public System.Threading.Tasks.Task<Events.FindEventsByAccountAKResponse> FindEventsByAccountAKAsync(Events.FindEventsByAccountAKRequest request)
        {
            return base.Channel.FindEventsByAccountAKAsync(request);
        }
        
        public Events.SearchEventResponse SearchEvent(Events.SearchEventRequest request)
        {
            return base.Channel.SearchEvent(request);
        }
        
        public System.Threading.Tasks.Task<Events.SearchEventResponse> SearchEventAsync(Events.SearchEventRequest request)
        {
            return base.Channel.SearchEventAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWsAPIEventPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWsAPIEventPort))
            {
                return new System.ServiceModel.EndpointAddress("https://bosdemo.enta.com.au/BosServices.dll/soap/IWsAPIEvent?OvwSessionId=F330592" +
                        "593FB4409B7B52FB32");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsAPIEventClient.GetBindingForEndpoint(EndpointConfiguration.IWsAPIEventPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsAPIEventClient.GetEndpointAddress(EndpointConfiguration.IWsAPIEventPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IWsAPIEventPort,
        }
    }
}
